version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 app.py"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rooot
      MYSQL_DATABASE: test
